### ISSUE TITLE
Nuxt v3 support

### ISSUE THREAD

**Issue by chrisnoden** [iWeltAG/pinia-cached-store#7] opened 2022-08-29 08:59 UTC
Following the instructions within Nuxt v3 (rc 8) does not work. Pinia is the recommended state management tool for Nuxt v3, so it would be excellent if the cached-store worked with it too.

**Comment by yrd** [comment] 2022-09-08 06:28
Still trying to reproduce this. This is what i've currently got: https://stackblitz.com/edit/github-av9tcd-qzghif?file=app.vue

**Comment by yrd** [comment] 2022-09-08 06:29
Still trying to reproduce this. This is what I've currently got: https://stackblitz.com/edit/github-av9tcd-qzghif?file=app.vue

cc @sfxcode

**Comment by yrd** [comment] 2022-09-08 06:31
Never mind the last one 🙈
I assume this is your error?

```
[nuxt] [request error] [unhandled] [500] window is not defined
  at Module.defineCachedStore (pinia-cached-store:100:48)  
  at eval (./app.vue:5:42)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:234:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:130:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:153:16)  
  at async eval (virtual:nuxt:./.nuxt/app-component.mjs:1:238)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:234:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:130:12)  
  at async request (./node_modules/vite-node/dist/client.mjs:153:16)  
  at async eval (./node_modules/nuxt/dist/app/entry.mjs:15:31)
```

**Comment by chrisnoden** [comment] 2022-09-08 07:13
Thanks, yes. I didn't include any errors because I was not sure what from the output was a Nuxt wrapper (where their errors can be very unhelpful) which might not be useful.

**Comment by yrd** [comment] 2022-09-12 05:42
This should be fixed in `v0.6.1`. If not feel free to reopen.

**Closed by yrd** 2022-09-12 05:42 UTC

**Comment by chrisnoden** [comment] 2022-09-14 08:13
Hi @yrd 
Thanks for looking into this so quickly.
I've created a basic project at [https://github.com/chrisnoden/nuxtv3-pinia-cached-store](https://github.com/chrisnoden/nuxtv3-pinia-cached-store)
If you attempt to run it you'll get the same `window is not defined` error. I suspect this is happening because Nuxt is rendering server-side. You may need to test for `window` and if undefined allow a fallback so the value/s can be returned from the source (an API in the case of my example).

**Comment by yrd** [comment] 2022-09-15 06:12
Thanks for the repo. Since I don't really have any experience with different SSR frameworks yet, I opted into not doing any magic around SSR in this project. You'll need to do the SSR checking manually, as documented here: https://github.com/iWeltAG/pinia-cached-store#manual-cache-writes-and-ssr

For Nuxt 3, you should be able to get running by doing this:

```ts
defineCachedStore({
  // ...
  caching: {
    storage: import.meta.env.SSR ? null : window.localStorage,
  },
})
```

The problem is we'd need to introduce a whole new build step (involving Vite and whatnot) in order to get access to `import.meta.env`, which frankly just isn't worth it for a small library like this. So instead you'll need to do this check manually for now. I guess you could argue with versatility here :wink:

**Comment by chrisnoden** [comment] 2022-09-15 07:30
Ahhh, makes perfect sense. My apologies for not reading that. I implemented that small change and it works. Thanks for providing such a useful little extension.

**Comment by yrd** [comment] 2022-09-15 11:40
Thanks, no problem!
